site_name: pitfallen.net
site_url: https://pitfallen.net/
theme:
  name: material
  font:
    text: Roboto
  icon:
    logo: material/console
  palette:
    scheme: slate
    primary: lime
    accent: lime # highlight colour
  features:
    - navigation.tracking # anchor tracking
    - navigation.expand # expand all subsections by default
    - navigation.footer
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/terryf82/
plugins:
  - social
  - macros
  - blog:
      blog_dir: .
      archive: false
      post_url_format: "{slug}"
      authors_profiles_toc: true
      author_profiles: true
  - search
  - tags
nav:
  - Home: index.md
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

  